# 矩阵计算

![样例](figure/求导1.jpg)
![样例](figure/求导2.jpg)
![样例](figure/求导3.jpg)
![样例](figure/求导4.jpg)

# 自动求导

In [1]:
import torch

x = torch.arange(4.)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)  # 设置存放梯度，相当于x = torch.arange(4., requires_grad=True)
x.grad  # 默认是None

In [3]:
y = 2 * torch.dot(x, x)
y  # 计算图

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
# Pytorch默认会累积梯度，需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

## 1.detach

In [6]:
x.grad.zero_()
y = x * x
u = y.detach()

z = u * x

In [7]:
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [8]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

## 2.控制流梯度

In [9]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad == d / a

tensor(True)

In [10]:
a = torch.randn(size=())
a, a.norm()

(tensor(-1.5063), tensor(1.5063))